packages:
  - 'packages/*'
  - '!packages/old'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true

overrides:
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  h3@<=1.15.4: '>=1.15.5'
  preact@>=10.28.0 <10.28.2: '>=10.28.2'
